### ISSUE TITLE
Can't load a sourcemap:  "_io.TextWrapper not subscriptable"

### ISSUE THREAD

**Issue by dbeard-groupon** [mattrobenolt/python-sourcemap#10]
I'm using pypy3, installed the pip package and my code looks like this: 

```
import sourcemap

minified = open('dealdetails.ios.jsbundle').read()
map_path = sourcemap.discover(minified)
index = sourcemap.loads(open('dealdetails.ios.sourcemap.js'))
```

Here's what I get:

```
Traceback (most recent call last):
  File "sm.py", line 6, in <module>
    index = sourcemap.loads(open('dealdetails.ios.sourcemap.js'))
  File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/sourcemap/__init__.py", line 22, in loads
    return cls().decode(source)
  File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/sourcemap/decoder.py", line 107, in decode
    if source[:4] == ")]}'" or source[:3] == ")]}":
TypeError: '_io.TextIOWrapper' object is not subscriptable
```

Anything obvious I'm doing wrong here? 
I'm trying to read a react-native produced sourcemap here which is in the "index map" format.

**Comment by mattrobenolt** [comment]
Sounds like you need `sourcemap.load`, not `sourcemap.loads`. `loads` expects a text object, while `load` works on a file-like object.

Alternatively, you can do `sourcemap.loads(open('dealdetails.ios.sourcemap.js').read())`

**Comment by dbeard-groupon** [comment]
Thanks for the quick reply! That gets me further, but now I end up with this: 

```
Traceback (most recent call last):
  File "sm.py", line 6, in <module>
    index = sourcemap.loads(open('dealdetails.ios.sourcemap.js').read())
  File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/sourcemap/__init__.py", line 22, in loads
    return cls().decode(source)
  File "/usr/local/Cellar/pypy3/5.5.0/libexec/site-packages/sourcemap/decoder.py", line 111, in decode
    sources = smap['sources']
KeyError: 'sources'
```

**Comment by mattrobenolt** [comment]
Hmm, iirc, React Native uses a style of source maps that this library doesn't support, called "indexed source maps". Basically sourcemaps nested within other sourcemaps.

We had to completely rewrite this stuff to support this process in Sentry. And this library has no concept of that.

**Comment by dbeard-groupon** [comment]
Ok, thought that might be the case. Appreciate the quick replies, thank you!

**Comment by deeksharm** [comment]
Hi, 

I want to add column name in header which is empty but without using Pandas, is there any way?
