### ISSUE TITLE
RFC:  lookup(self, line)

### ISSUE THREAD

**Issue by sebastienbarre** [mattrobenolt/python-sourcemap#8]
Hi, and thanks for the work on this project.

Would you be open to a PR that would add a new `lookup` function accepting *only* a line number? Our coverage tool only reports line locations, and even I call the current [`lookup`](https://github.com/mattrobenolt/python-sourcemap/blob/master/sourcemap/objects.py#L61) with an arbitrary column number such as 1 or 0, I end up with `IndexError` exceptions sporadically.
Thanks

**Comment by mattrobenolt** [comment]
How would a lookup without a column number even work? With only a line number, it's simply not enough information to index into the sourcemap. Unless I'm missing something and this can be done, but from my understanding it's just required to get to the right symbol.

**Comment by sebastienbarre** [comment]
Thanks for the quick reply @mattrobenolt 

As you know, there are many different ways to generate a source map that still complies with the source map specs. Webpack, in this example, can generate [quite a few](https://webpack.github.io/docs/configuration.html#devtool). Many of them do not mangle your original source lines together, e.g. your original source lines are kept separate. In this context, you "only" need the mapping between source lines, which is convenient because line numbers is the only metric our code coverage tool, [alex-seville/blanket](https://github.com/alex-seville/blanket), reports. It would greatly help if a new `lookup` method could accept a line number only, or if the current `lookup` could support a column number set to `None` (or anything non-numeric), and return early with the remapped line number, and the same column number (e.g. `None` or anything non-numeric).

Thank you

**Comment by sebastienbarre** [comment]
Would a PR be OK?

**Comment by mattrobenolt** [comment]
Sure. :)

--
Matt Robenolt
@mattrobenolt




On Mon, Sep 12, 2016 at 8:21 PM -0700, "Sébastien Barré" <notifications@github.com> wrote:












Would a PR be OK?
